version: "3.9"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "8001:80"
    networks:
      - "web.network"
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"
    networks:
      - "web.network"
    volumes:
      - mongodata:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  redis:
    container_name: "redis"
    image: redis:alpine
    ports: 
      - "6379:6399"
    networks:
      - "web.network"
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  web:
    build: .
    ports:
      - "8000"
    volumes:
      - ".:/app"
    restart: "always"
    environment:
      - Replica= {{.Task.Name}}
    depends_on:
      - mongo
    networks:
      - "web.network"
    deploy:
      replicas: 1
networks:
  web.network:
volumes:
  mongodata:
  mongodb_config:

